package br.com.grupojcr.enumerator;

public enum LocalizacaoChamado {
	ADMINISTRATIVO_FINANCEIRO("ADMINISTRATIVO/FINANCEIRO"),
	CONTABILIDADE_CONTROLADORIA("CONTABILIDADE/CONTROLADORIA"),
	DIRETORIA("DIRETORIA"),
	GERENCIA_GERAL("GERÊNCIA GERAL"),
	GUARITA("GUARITA"),
	JARDIM_CANAA("JARDIM CANAÃ"),
	JURIDICO("JURÍDICO"),
	LOGTRADE("LOGTRADE"),
	OPERACOES_IMOBILIARIAS("OPERAÇÕES IMOBILIÁRIAS"),
	PONTAL_ESCRITORIO("PONTAL ESCRITÓRIO"),
	PONTAL_ESTACIONAMENTO("PONTAL ESTACIONAMENTO"),
	PORTO_PONTAL("PORTO PONTAL"),
	PRESIDENCIA("PRESIDÊNCIA"),
	RECEPCAO("RECEPÇÃO"),
	RH("RH"),
	SERVIDORES("SERVIDORES"),
	TI("TI"),
	VALUATION("VALUATION");
	
	private String descricao;
	
	private LocalizacaoChamado(String descricao) {
		this.descricao = descricao;
	}

	public String getDescricao() {
		return descricao;
	}
	
}
